[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_project = "3kAVGR8RrGNnutMWiVYi2DVs12NuhKhtKGQpn1TPQy7V"

[programs.devnet]
anchor_project = "3kAVGR8RrGNnutMWiVYi2DVs12NuhKhtKGQpn1TPQy7V"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/enyu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
